### ISSUE TITLE
Hide Home Button

### ISSUE THREAD

**Issue by berho** [LotarProject/dokuwiki-template-bootstrap3#124]
Hello,
how can i hide the home button in the navbar of my side ? I have some links in the :navbar page but the home button is always displayed right of them.

Regards,
berho

**Comment by LotarProject** [comment]
Hi berho.
The home links is placed inside the ``navbar.html`` hook.

At your disposal,
Joseph

**Comment by berho** [comment]
Thanks, found and fixed. Why do you use an extra file? This can be done in :navbar but if you use navbar.html than IMHO the home button sould be the first one.

Regards,
berho
PS: your extentions are all great :)

**Comment by LotarProject** [comment]
The ``navbar.html`` is the first solution for a navbar. In the future ``navbar.html`` will be dropped, because the ``:navbar`` DokuWiki hook is more easy to maintain and is namespace compliant.

This is not the first request or question about the home-page link. I have in planning a new out-of-the-box config to add or remove the home-link without edit the ``navbar.html`` file.

Thanks for using my template and extensions :)

Best regards,
Joseph

**Comment by polyzen** [comment]
Great to hear, Joseph.
