### ISSUE TITLE
Mobile View borked when using many tags

### ISSUE THREAD

**Issue by duenni** [LotarProject/dokuwiki-template-bootstrap3#152]
Hi there,

we're using many tags in our wiki and at a certain amount the view from mobile devices is borked because the tags are not wrapped. See screenhots below.

**Good:**
![right](https://cloud.githubusercontent.com/assets/4258185/13297339/3081a3d8-db32-11e5-844b-25db7f2a3bc2.PNG)

**Wrong:**
![wrong](https://cloud.githubusercontent.com/assets/4258185/13297373/5821a92e-db32-11e5-91f9-4bd993f003d1.PNG)

Thanks in advance for looking into this!

**Comment by hvarga** [comment]
I am also interested in this. It would be great if tags can perform line wrapping. Similar like in any text editor when performing wrapping of text.

**Comment by hvarga** [comment]
I tried your fix and works as I imagined. But there is just one minor issue from my side.

While the wrapping of the tags now works, I am experiencing one issue. If you look at the screenshot bellow you can see that the text of a tag can be separated from the tag icon. Of course, this only happens when there is a need to wrap the tags on two or more lines.

From my point of view, this looks kind of ugly and out of place.

I would say that this is just an aesthetic issue but I would like that the wrapping functionality can't separate tag icon from tag text.

What do you think @LotarProject?

Let me know if you need the exact steps to reproduce this issue.

![tag-icon](https://cloud.githubusercontent.com/assets/2044225/13404011/07177254-df18-11e5-832b-f4e4eaceda6f.png)

**Comment by AlekSet** [comment]
Some `nowrap` needed. Except this, everything is very good now.

**Comment by hvarga** [comment]
Great, thanks for your confirmation. This is for sure the best template for DokuWiki! Keep up the good work.
