### ISSUE TITLE
Change ordered lists numbering

### ISSUE THREAD

**Issue by sanctus17** [LotarProject/dokuwiki-template-bootstrap3#221]
Hi there,

I would like to change to numbering in ordered lists (from decimal to upper-alpha on the first OL level).

However, I don't seem to find the appropriate CSS file. I tried editing 'template.less' in lib/tpl/bootstrap3/css/ but that did not seem to do the trick.

Any advice on where to find the appropriate list-style-type?

Thank you, any help would be very much appreciated!

T

**Comment by LotarProject** [comment]
Hi! Editing ``template.less`` file is unsafe because this is overwritten during update of template. I suggest to see this page https://www.dokuwiki.org/devel:css can explain a secure method to customize a template using user-defined CSS files
I have created Advanced plugin (https://www.dokuwiki.org/plugin:advanced) for manage this files present in ``<dokuwiki>/conf`` directory.

At your disposal,
Joseph

**Comment by LotarProject** [comment]
This is a snippet from template CSS:
```.css
/* Ordered list style */
ol             { list-style: decimal outside; }   /* Decimal: 1. 2. 3. ...              */
ol ol          { list-style-type: lower-alpha; }  /* Alpha (lowercase): a. b. c. ...    */
ol ol ol       { list-style-type: upper-roman; }  /* Roman (uppercase): I. II. III. ... */
ol ol ol ol    { list-style-type: upper-alpha; }  /* Alpha (uppercase): A. B. C. ...    */
ol ol ol ol ol { list-style-type: lower-roman; }  /* Roman (lowercase): i. ii. iii. ... */
```

and this is a solution for you:
```.css
ol             { list-style: upper-alpha outside; }
ol ol          { list-style-type: decimal; }
[...]
```

Joseph

**Comment by sanctus17** [comment]
Awesome, thank you very much!
