### ISSUE TITLE
Configuration pageIcons

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [LotarProject/dokuwiki-template-bootstrap3#253]
I have some problems with the configuration of the pageIcons:

- The pageicon "feed" is a little bit curious, because it always sets the feed to changes of the whole wiki. But when I click on this feed symbol I want to subscribe to the namespace of this page.
- The pageicon "help" doesn't have any effect.

Versions:
  * Bootstrap3 2016-07-05
  * DokuWiki Release 2015-08-10a

**Comment by LotarProject** [comment]
Hi, thanks for reporting this issue.

  - for "feed" pageicon i have changed the url and i have added the current NS
  - the "help" pageicon work only if in the current NS exist a page called "help" (i have added this hook into documentation :P)

The fix for "feed" will be upcoming for next release in this month (v2016-10).
