### ISSUE TITLE
Pagelist-plugin - compatibility - row height of tables in Internet Explorer

### ISSUE THREAD

**Issue by martk70** [LotarProject/dokuwiki-template-bootstrap3#278]
### Description

[Description of the bug or feature]

update 3-3-2017: 
sudden exceptional row height in IE with tag-, task- and pagelist-plugins.
I found this behaviour also in the TASK-plugin. Both plug-ins (task and tag) depend on the pagelist plugin for their output of tables, so the issue seems to be there (I will therefore change the issue title TAG -> PAGELIST). Discussed things with the plug-in maintainer who asked some good questions. This behaviour does not happen with the standard dokuwiki template.

### Steps to Reproduce
tag plugin:  e.g. with this syntax for listing all pages in namespace with the tag 'open'. {{topic>qhse:qpr?open}}

live example on http://www.mvak.nl/a/doku.php?id=mappa:start (click folded 'blog archive' link).
Markup: 
{{archive>:blog:mappa?*}}
♣test
{{topic>:blog:mappa?test}}

**Expected behavior:** [What you expected to happen]
**Actual behavior:** [What actually happened]
example above

### Versions

  * [Bootstrap3 Template] Latest
  * [DokuWiki] latest
  * [Plugin] latest
  * [Browser]  IE 11.0.8

### Screenshots or Logs

[Paste your logs or attach the screenshot]

### Sample Page
http://www.mvak.nl/a/doku.php?id=mappa:start (click folded 'blog archive' link).

**Comment by atiq4pk** [comment]
First thing is that "I am not expert" I have solution which might work:
In my opinion the <td> tag of the pagelist has class "page" under "article". Therefore it is taking min height from css because of the following style: 
```
article .page {
    min-height: 400px;
  }
```
In the template.less of bootstrap3/css, if we change this value with 20px, then it may solve the problem.  But it will also effect the page height if page length is less than 400px.
You may achieve this by adding this style to userstyle.css.

Or you may use "simplelist" style to avoid this problem in IE but it us some thing else..
