### ISSUE TITLE
h1 is too big

### ISSUE THREAD

**Issue by Oreolek** [LotarProject/dokuwiki-template-bootstrap3#284]
Can there be an option to make the headings smaller? Or at least the h1 heading, it's way too big compared to h2. Look at Github, the biggest heading has the `font-size` of `32px`, not a whopping `56px`.

**Comment by LotarProject** [comment]
Hi @Oreolek,
Bootstrap3 template use the Bootstrap's size value for Headings. I suggest to change the size of Headings via CSS using ``userall.css`` (or ``userstyle.css``) file placed in ``<dokuwiki>/conf/`` directory or by using my Advanced Plugin (https://www.dokuwiki.org/plugin:advanced).

This is the default Bootstrap (v3.3.7) heading sizes:

```.css
h1, .h1 {
  font-size: 36px;
}
h2, .h2 {
  font-size: 30px;
}
h3, .h3 {
  font-size: 24px;
}
h4, .h4 {
  font-size: 18px;
}
h5, .h5 {
  font-size: 14px;
}
h6, .h6 {
  font-size: 12px;
}
```

**Comment by aubreyz** [comment]
That is the answer -- but just to get back to issue as posted - the reason @Oreolek is seeing such a big header font is because some of the themes he might have chosen in configuration use massive (non bootstrap standard) font sizes. For example the Cyborg theme. The above would override all themes (which might also be user selectable) 

The question for me is where one would change the CSS to alter heading sizes (or indeed other things) in one theme only if the themes are held offline.
