### ISSUE TITLE
Lists not working on sidebars (<li> tags stripped from code)

### ISSUE THREAD

**Issue by nospheratt** [LotarProject/dokuwiki-template-bootstrap3#46]
First of all, let me tell you, the Bootstrap3 template is awesome. I’ve been using Vector since 2011, this was the first template that tempted me to switch and I love it. So, thank you!

The issue: I updated the template yesterday and when I loaded the wiki in the browser, it was stripping the ``<li>`` tags from all the lists I have on the sidebars. The tags appeared in the source code, but not in the browser. I tested on Firefox, IE and Chrome.

After a lot of fiddling, I’ve finally found the cause: these two lines in scrip.js (284 and 285):

``` 
$dw_aside.find('ul.nav li span').unwrap();
$dw_aside.find('ul.nav li a').unwrap(); 
```

I've commented them and the lists are working again. I don’t know if the stripping of tags is intentional, or if commenting the lines will cause problems elsewhere, but I thought I’d share it since it took me two days to discover what was causing the problem. 

If I can help with anything, just let me know.  :)

**Comment by LotarProject** [comment]
Hi! Thank you for reporting this issue and investigated the causes :)

I have intentional stripped the tags because DokuWiki add inside the "li" tag other tags ("div" and/or "span"). The Bootstrap Nav component not work properly with this tags.

In my last commit (ff19bbd) i have added a specific CSS selector to optimize the result and solve the conflicts.

Your help and that of others is welcome ;)

Best regards,
Joseph

**Comment by nospheratt** [comment]
I've added the changes to script.js and it works perfectly. Thank you! =)

If/when I have something else to contribute, I'll let you know. If you need my help with something specific (I'm not a coder, but I can help with beta testing and some debugging), send me an email. :)
