### ISSUE TITLE
Issue with Bootswatch Themes

### ISSUE THREAD

**Issue by dekborangeice** [LotarProject/dokuwiki-template-bootstrap3#71]
I am attempting to customize a Bootswatch theme.

If I use Configuration Manager to point to Bootswatch.com, I get a nice pretty theme that colors my screen including the sidebars 
![superhero_from_dotcom](https://cloud.githubusercontent.com/assets/13863705/9349251/17a65284-4611-11e5-9a5a-f6bc6d2fd17d.jpg)

However, if I download the bootstrap.css file and bootstrap.min.css file from Bootswatch and then try to activate those as a vanilla bootstrap file, I get the following
![superhero_replace_vanilla](https://cloud.githubusercontent.com/assets/13863705/9349263/4a588148-4611-11e5-8f15-d59b69ae06b3.jpg)

**Comment by LotarProject** [comment]
Hi! It's correct, because i have added a custom style for the default and optional Bootstrap theme. I suggest this config:

  * ``bootstrapTheme``: ``custom`` (Customized Bootstrap theme)
  * ``customTheme``: url of your custom Bootswatch theme (eg. ``/dokuwiki/lib/tpl/bootstrap3/assets/custom/bootswatch.min.css``)

Best regards,
Joseph
