### ISSUE TITLE
Pagetools more accessible

### ISSUE THREAD

**Issue by Qemwen** [LotarProject/dokuwiki-template-bootstrap3#73]
Hi,

I'm wondering if it is possible to add the pagetools menu to the page itself (rather than hidden in a dropdown menu in the navbar). In Dokuwiki's default template this exists and I really miss it in the bootstrap3 template. Is it possible to add it myself or could you pick it up as a possible future feature?

Thanks in advance for your response.

Kind Regards, 
Caroline

![pagetools](https://cloud.githubusercontent.com/assets/14006347/9534385/55dd3c8a-4d18-11e5-9e07-f263fd80feb0.png)

**Comment by LotarProject** [comment]
Yes! I'm to work for a new idea for the template and for all Tools Menu (User, Page and Site).

A new configuration setting (a drop-down menu) to set your prefered layout:

  * Big Menu (default)
  * Individual Menus
  * Toolbar (work in progress)
  * Default DokuWiki style

**Comment by alqu** [comment]
Actually, this is one of my most wanted features... since this thing is so important: the edit button is one of the most used actions at all.

Thanks for your awesome work!

**Comment by LotarProject** [comment]
Hi! This is my implementation of accessible page tools (like DokuWiki):

![image](https://cloud.githubusercontent.com/assets/1824717/9799942/818187f4-580a-11e5-9567-66145d514c03.png)

**Comment by alqu** [comment]
Thanks! Looks very good.

**Comment by Qemwen** [comment]
Awesome! Thank you.

**Comment by LotarProject** [comment]
Added the animations on mouse hover

![test](https://cloud.githubusercontent.com/assets/1824717/9819188/e4969d78-58ac-11e5-998d-5d8ebdfac71d.gif)

**Comment by worstboy32** [comment]
Looking good :)

**Comment by LotarProject** [comment]
I have pushed a commit (fbf9b39) that introduces a new experimental and accessible Page Tools.

**Comment by alqu** [comment]
Cool! I reinstalled the template and now the pagetools are there.

There is only one thing that breaks the pagetools: as soon as there are more things from plugins, then the old logic with
```html
<li>
  <a href="/start?do=export_pdf" class="action text-muted export_pdf" rel="nofollow" title="PDF exportieren"><span>PDF exportieren</span></a>
</li>
<li>
  <a href="/start?do=export_odt" class="action text-muted export_odt" rel="nofollow" title="ODT exportieren"><span>ODT exportieren</span></a>
</li>
```
Sure... because you adjusted the default tools with 
```html
...
<a href="/start?do=backlink" class="action text-muted backlink" rel="nofollow" title="Links hierher">
  <i class="fa fa-fw fa-link"></i><span class="sr-only"> Links hierher</span>
</a>
...
```
Then it looks like this:
![2015-09-12 bootstrap3 menu](https://cloud.githubusercontent.com/assets/12250845/9829845/f5de77f8-5916-11e5-88a0-f9241763d147.png)
...hovering over it looks like that:
![2015-09-12 bootstrap3 menu-hover](https://cloud.githubusercontent.com/assets/12250845/9829848/06cefbdc-5917-11e5-9b7f-acddb88086fd.png)

Do you have an idea what can be done with those? I quickly looked into `tpl:page_tools.php` and found that there is no `</i>` int those additional links. And that is probably a hint in the right direction.
I mean this line:
https://github.com/LotarProject/dokuwiki-template-bootstrap3/commit/fbf9b394142ff047fb7291337b35bedd45a1f712#diff-af293c1bd87b929f95aaf2f7086e0b4bR23

Thanks for your help! :smile:

**Comment by worstboy32** [comment]
Works perfectly for me. Awesome!
Just two small things.

I would love the buttons a little bigger maybe make it a config setting.
For new users it's quite hard to notice the buttons I believe.

Secondly, I'd like to be able to remove the page tools from the navbar.
I've tried disabling it in the config options but when I disable Page tools it also removes the sidebar you've just added.

Other than that it's great!

**Comment by LotarProject** [comment]
Hi! In my last commit i have fixed some issue for the Page Tools. In this fix i have introduced a default icon for the plugins (eg. otd exporter, etc). I'm to work to integrate the original or a similar icon.

Joseph

**Comment by worstboy32** [comment]
Thanks,
I saw you did some changes with the admin menu too.
But for me it's just completely blank now when I try to open it.
http://i.imgur.com/U9ONl5e.png

**Comment by LotarProject** [comment]
Hi! Fixed this issue (#80) in last commit a94b086

Joseph

**Comment by alqu** [comment]
Awesome! Works really good.

Thanks for your work!

**Comment by worstboy32** [comment]
Yeah works perfect now.
Thanks!

**Comment by martk70** [comment]
I am positive as well! But I am a keyboard fan and it seems some access key support has been dropped  especially for editing?  
In Firefox I miss the Alt-Shift-E for editing.
In IE Alt-E selects the button, and with <enter> opens edit mode. Nifty, and quite alright, but not as quick as the Dokuwiki standard. https://www.dokuwiki.org/accesskeys

**Comment by LotarProject** [comment]
Hi! The access key is not dropped. I have tested in different DokuWiki installations with my template and all access key works.

At your disposal,
Joseph

**Comment by martk70** [comment]
Hello! Thanks for your efforts - seems the problem is not reproduceable, but still there for me.

Thing is that both installs (intranet Ubuntu server and my personal provider) have this 'issue' (Alt-Shift E in firefox not working).

Perhaps others will ring a bell - in the meantime its  not that important.



Thanks again.

Martin


	Martin van der Knijff, Gouda

	http://www.mvak.nl

	0182-537217




----- Original Message ----

From: Giuseppe Di Terlizzi 

To: LotarProject/dokuwiki-template-bootstrap3 

Cc: martk70 

Sent: Maa, 21 Sep 2015 22:38

Subject: Re: [dokuwiki-template-bootstrap3] Pagetools more accessible (#73)




	Hi! The access key is not dropped. I have tested in different DokuWiki installations with my template and all access key works.

	At your disposal,

	Joseph
