### ISSUE TITLE
Difference in internal and custom bootswatch theme setting

### ISSUE THREAD

**Issue by innuendonh** [LotarProject/dokuwiki-template-bootstrap3#89]
The sandstone theme has different behaviors when using the internal setting and when applying the custom setting using URL `https://maxcdn.bootstrapcdn.com/bootswatch/3.3.5/sandstone/bootstrap.min.css` (that is the same that is applied by the them as I understand).

The difference is that the "internal" theme transforms everything in uppercase, while manually setting the URL of the CDN has the expected effect.

I experience this on DokuWiki 2015-08-10a "Detritus"

**Comment by LotarProject** [comment]
Hi! Can you explain with a screenshot ? This behavior is present with the last release of template ?

From the 3.3.5 release of Bootswatch some people have problem with a fonts.

**Comment by cbf305** [comment]
I just installed DokuWiki (2017-02-19E "FRUSTERICK MANNERS") and I can confirm this still seems to be an issue.  It's using Bootswatch 3.3.7 and everything on the Sandstone theme only is all uppercase.  I will be using this for an intranet so having everything in all caps will drive people mad.  Also the font size seems to be small compared to the other themes.

When loading from the Bootswatch CDN everything works as expected as well as the overall font size seems to be a little larger, which is nice.

So I took the CDN version and uploaded that to the server, temporarily renaming the original file and then set it to use the internal version, and the CSS file won't load at all.  So I'll leave it on the CDN version for now, but it'd be nice to have the internal version working since this is for an intranet.

I'm attaching screenshots of the syntax sample page:

Before (internal CSS):
![before](https://user-images.githubusercontent.com/2612500/38023479-69a83c4a-3250-11e8-839a-415c79f2b14b.png)

After (Bootswatch CDN):
![after](https://user-images.githubusercontent.com/2612500/38023484-6c47c29a-3250-11e8-97ca-ce5e83efa282.png)

.
